using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DotNetCore.Collections.Paginable.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public class SolidPageExtensionsGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "DotNetCore.Collections.Paginable.SolidPageExtensionsForAttribute";

    private const string AttributeSource = """
// <auto-generated/>
#nullable enable

namespace DotNetCore.Collections.Paginable
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class SolidPageExtensionsForAttribute : global::System.Attribute
    {
        public SolidPageExtensionsForAttribute(
            string ormName,
            string sourceTypeFullName,
            string sourceParamName,
            string pageTypeName,
            string paginableTypeName,
            string factoryTypeName,
            string helperTypeName)
        {
            OrmName = ormName;
            SourceTypeFullName = sourceTypeFullName;
            SourceParamName = sourceParamName;
            PageTypeName = pageTypeName;
            PaginableTypeName = paginableTypeName;
            FactoryTypeName = factoryTypeName;
            HelperTypeName = helperTypeName;
        }

        public string OrmName { get; }
        public string SourceTypeFullName { get; }
        public string SourceParamName { get; }
        public string PageTypeName { get; }
        public string PaginableTypeName { get; }
        public string FactoryTypeName { get; }
        public string HelperTypeName { get; }
        public string? GenericConstraint { get; set; }
        public bool HasAdditionalQueryFunc { get; set; }
        public bool ToPaginableHasAdditionalQueryFunc { get; set; }
        public bool HasIncludeNestedMembers { get; set; }
        public bool HasAsync { get; set; }
        public string? AsyncCountExpression { get; set; }
        public string? AsyncFetchExpression { get; set; }
        public string? AsyncFetchMethodName { get; set; }
        public bool AsyncFetchReturnsList { get; set; }
        public bool SourceTypeIsNonGeneric { get; set; }
        public string? SyncCountCastExpression { get; set; }
        public string? ToPaginableSourceParamName { get; set; }
        public bool ForwardAsyncCancellationToken { get; set; } = true;
        public string? SourceDescriptor { get; set; }
        public string? PageDescriptor { get; set; }
        public string? SourceExample { get; set; }
    }
}
""";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("SolidPageExtensionsForAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
        });

        var classDeclarations = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => GetConfig(ctx))
            .Where(static c => c is not null);

        context.RegisterSourceOutput(classDeclarations, static (ctx, config) =>
        {
            if (config is null) return;
            var source = GenerateExtensions(config);
            ctx.AddSource($"{config.OrmName}SolidPageExtensions.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static GeneratorConfig? GetConfig(GeneratorAttributeSyntaxContext ctx)
    {
        var classSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
        var attr = ctx.Attributes.FirstOrDefault();
        if (attr is null) return null;

        var args = attr.ConstructorArguments;
        if (args.Length < 7) return null;

        var config = new GeneratorConfig
        {
            Namespace = classSymbol.ContainingNamespace.IsGlobalNamespace
                ? ""
                : classSymbol.ContainingNamespace.ToDisplayString(),
            ClassName = classSymbol.Name,
            OrmName = args[0].Value?.ToString() ?? "",
            SourceTypeFullName = args[1].Value?.ToString() ?? "",
            SourceParamName = args[2].Value?.ToString() ?? "source",
            PageTypeName = args[3].Value?.ToString() ?? "",
            PaginableTypeName = args[4].Value?.ToString() ?? "",
            FactoryTypeName = args[5].Value?.ToString() ?? "",
            HelperTypeName = args[6].Value?.ToString() ?? "",
        };

        foreach (var named in attr.NamedArguments)
        {
            switch (named.Key)
            {
                case "GenericConstraint":
                    config.GenericConstraint = named.Value.Value?.ToString();
                    break;
                case "HasAdditionalQueryFunc":
                    config.HasAdditionalQueryFunc = (bool)named.Value.Value!;
                    break;
                case "ToPaginableHasAdditionalQueryFunc":
                    config.ToPaginableHasAdditionalQueryFunc = (bool)named.Value.Value!;
                    break;
                case "HasIncludeNestedMembers":
                    config.HasIncludeNestedMembers = (bool)named.Value.Value!;
                    break;
                case "HasAsync":
                    config.HasAsync = (bool)named.Value.Value!;
                    break;
                case "AsyncCountExpression":
                    config.AsyncCountExpression = named.Value.Value?.ToString();
                    break;
                case "AsyncFetchExpression":
                    config.AsyncFetchExpression = named.Value.Value?.ToString();
                    break;
                case "AsyncFetchMethodName":
                    config.AsyncFetchMethodName = named.Value.Value?.ToString();
                    break;
                case "AsyncFetchReturnsList":
                    config.AsyncFetchReturnsList = (bool)named.Value.Value!;
                    break;
                case "SourceTypeIsNonGeneric":
                    config.SourceTypeIsNonGeneric = (bool)named.Value.Value!;
                    break;
                case "SyncCountCastExpression":
                    config.SyncCountCastExpression = named.Value.Value?.ToString();
                    break;
                case "ToPaginableSourceParamName":
                    config.ToPaginableSourceParamName = named.Value.Value?.ToString();
                    break;
                case "ForwardAsyncCancellationToken":
                    config.ForwardAsyncCancellationToken = (bool)named.Value.Value!;
                    break;
                case "SourceDescriptor":
                    config.SourceDescriptor = named.Value.Value?.ToString();
                    break;
                case "PageDescriptor":
                    config.PageDescriptor = named.Value.Value?.ToString();
                    break;
                case "SourceExample":
                    config.SourceExample = named.Value.Value?.ToString();
                    break;
            }
        }

        return config;
    }

    private static string GenerateExtensions(GeneratorConfig config)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using DotNetCore.Collections.Paginable.Internal;");

        var sourceNs = ExtractNamespace(config.SourceTypeFullName);
        if (!string.IsNullOrEmpty(sourceNs))
            sb.AppendLine($"using {sourceNs};");

        if (!string.IsNullOrEmpty(config.Namespace))
        {
            sb.AppendLine($"namespace {config.Namespace}");
            sb.AppendLine("{");
        }

        var indent = string.IsNullOrEmpty(config.Namespace) ? "" : "    ";
        var constraint = config.GenericConstraint is null ? "" : $" where T : {config.GenericConstraint}";

        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// Extensions for solid page for {config.OrmName}");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}partial class {config.ClassName}");
        sb.AppendLine($"{indent}{{");

        var memberIndent = indent + "    ";

        GenerateToPaginable(sb, memberIndent, config, constraint);
        GenerateGetPage(sb, memberIndent, config, constraint);

        if (config.HasAsync)
            GenerateToPaginableAsync(sb, memberIndent, config, constraint);

        if (!string.IsNullOrEmpty(config.AsyncFetchExpression))
            GenerateGetPageAsync(sb, memberIndent, config, constraint);

        sb.AppendLine($"{indent}}}");

        if (!string.IsNullOrEmpty(config.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string? ExtractNamespace(string fullTypeName)
    {
        var s = fullTypeName;
        var idx = s.IndexOf('<');
        if (idx >= 0) s = s.Substring(0, idx);
        var dot = s.LastIndexOf('.');
        return dot > 0 ? s.Substring(0, dot) : null;
    }

    private static void AppendDoc(StringBuilder sb, string indent, string sourceParamName, string sourceParamDoc,
        string typeParamDoc, IEnumerable<(string Name, string Doc)> paramDocs, string example,
        string[] summaryLines, bool withExceptions, bool isAsync)
    {
        sb.AppendLine($"{indent}/// <summary>");
        foreach (var line in summaryLines)
            sb.AppendLine($"{indent}/// {line}");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}/// <typeparam name=\"T\">{typeParamDoc}</typeparam>");
        sb.AppendLine($"{indent}/// <param name=\"{sourceParamName}\">{sourceParamDoc}</param>");

        foreach (var (name, doc) in paramDocs)
            sb.AppendLine($"{indent}/// <param name=\"{name}\">{doc}</param>");

        sb.AppendLine($"{indent}/// <returns></returns>");

        if (withExceptions)
        {
            sb.AppendLine($"{indent}/// <exception cref=\"ArgumentNullException\"><paramref name=\"{sourceParamName}\"/> is <c>null</c>.</exception>");
            sb.AppendLine($"{indent}/// <exception cref=\"ArgumentOutOfRangeException\">");
            if (isAsync)
            {
                sb.AppendLine($"{indent}/// <paramref name=\"pageNumber\"/> is less than one, <paramref name=\"pageSize\"/> is less than one, or");
                sb.AppendLine($"{indent}/// <paramref name=\"pageNumber\"/> points past the last page.");
            }
            else
            {
                sb.AppendLine($"{indent}/// <paramref name=\"pageNumber\"/> is less than one, or <paramref name=\"pageSize\"/> is less than one.");
            }
            sb.AppendLine($"{indent}/// </exception>");
        }

        sb.AppendLine($"{indent}/// <example>");
        sb.AppendLine($"{indent}/// <code>");
        foreach (var line in example.Split('\n'))
            sb.AppendLine($"{indent}/// {line.TrimEnd('\r')}");
        sb.AppendLine($"{indent}/// </code>");
        sb.AppendLine($"{indent}/// </example>");
    }

    private static void GenerateToPaginable(StringBuilder sb, string indent, GeneratorConfig config, string constraint)
    {
        var src = SourceTypeName(config);
        var p = config.ToPaginableSourceParamName ?? config.SourceParamName;
        var sd = SourceDescriptor(config);
        var pd = PageDescriptor(config);

        var aqf = config.ToPaginableHasAdditionalQueryFunc
            ? $"Func<{src}, {src}>? additionalQueryFunc = null"
            : "";
        var inm = config.HasIncludeNestedMembers ? "bool? includeNestedMembers = null" : "";
        var extraParams = GetExtraParams(aqf, inm);
        var factoryGenericArg = config.SourceTypeIsNonGeneric ? "<T>" : "";
        var forward = GetToPaginableForwardArgs(config);

        var summary = new[] { $"Make original {sd} result to {pd} collection." };
        const string typeParamDoc = "element type of your enumerable result";

        AppendDoc(sb, indent, p, sd, typeParamDoc,
            ToPaginableParamDocs(config, withPageSize: false),
            ToPaginableExample(config, p),
            summary, withExceptions: false, isAsync: false);
        sb.AppendLine($"{indent}public static {config.PaginableTypeName}<T> ToPaginable<T>(this {src} {p}, int? limitedMemberCount = null{extraParams}){constraint}");
        sb.AppendLine($"{indent}    => {config.FactoryTypeName}.CreatePageSet{factoryGenericArg}({p}, limitedMemberCount: limitedMemberCount{forward});");
        sb.AppendLine();

        AppendDoc(sb, indent, p, sd, typeParamDoc,
            ToPaginableParamDocs(config, withPageSize: true),
            ToPaginableExample(config, p),
            summary, withExceptions: false, isAsync: false);
        sb.AppendLine($"{indent}public static {config.PaginableTypeName}<T> ToPaginable<T>(this {src} {p}, int pageSize, int? limitedMemberCount = null{extraParams}){constraint}");
        sb.AppendLine($"{indent}    => {config.FactoryTypeName}.CreatePageSet{factoryGenericArg}({p}, pageSize, limitedMemberCount{forward});");
        sb.AppendLine();
    }

    private static IEnumerable<(string, string)> ToPaginableParamDocs(GeneratorConfig config, bool withPageSize)
    {
        if (withPageSize) yield return ("pageSize", "page size");
        yield return ("limitedMemberCount", "limited member count");
        if (config.HasIncludeNestedMembers) yield return ("includeNestedMembers", "include nested members");
        if (config.ToPaginableHasAdditionalQueryFunc) yield return ("additionalQueryFunc", "");
    }

    private static void GenerateGetPage(StringBuilder sb, string indent, GeneratorConfig config, string constraint)
    {
        var src = SourceTypeName(config);
        var p = config.SourceParamName;
        var sd = SourceDescriptor(config);

        var aqf = config.HasAdditionalQueryFunc ? $"Func<{src}, {src}>? additionalQueryFunc = null" : "";
        var inm = config.HasIncludeNestedMembers ? "bool includeNestedMembers = false" : "";
        var extraParams = GetExtraParams(aqf, inm);
        var extraArgs = GetExtraArgs(config.HasAdditionalQueryFunc, config.HasIncludeNestedMembers);
        var countExpr = $"{config.HelperTypeName}.Count({p})";
        if (!string.IsNullOrEmpty(config.SyncCountCastExpression))
            countExpr += config.SyncCountCastExpression;
        var pageCtorArgs = config.HasAdditionalQueryFunc || config.HasIncludeNestedMembers
            ? $"{p}, pageNumber, pageSize, {countExpr}{extraArgs}"
            : $"{p}, pageNumber, pageSize, {countExpr}";
        var delegateGeneric = config.SourceTypeIsNonGeneric ? "<T>" : "";

        var summary = new[] { $"Get specific page from original {sd} source" };
        var sourceParamDoc = $"original {sd} source";
        var typeParamDoc = $"element type of your {sd} source";

        AppendDoc(sb, indent, p, sourceParamDoc, typeParamDoc,
            GetPageParamDocs(config, withPageSize: false),
            GetPageExample(config, p, withPageSize: false),
            summary, withExceptions: false, isAsync: false);
        sb.AppendLine($"{indent}public static IPage<T> GetPage<T>(this {src} {p}, int pageNumber{extraParams}){constraint}");
        sb.AppendLine($"{indent}    => GetPage{delegateGeneric}({p}, pageNumber, PaginableSettingsManager.Settings.DefaultPageSize{(config.HasAdditionalQueryFunc ? ", additionalQueryFunc" : "")}{(config.HasIncludeNestedMembers ? ", includeNestedMembers" : "")});");
        sb.AppendLine();

        AppendDoc(sb, indent, p, sourceParamDoc, typeParamDoc,
            GetPageParamDocs(config, withPageSize: true),
            GetPageExample(config, p, withPageSize: true),
            summary, withExceptions: true, isAsync: false);
        sb.AppendLine($"{indent}public static IPage<T> GetPage<T>(this {src} {p}, int pageNumber, int pageSize{extraParams}){constraint}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    if ({p} is null)");
        sb.AppendLine($"{indent}        throw new global::System.ArgumentNullException(nameof({p}), $\"{{nameof({p})}} can not be null.\");");
        sb.AppendLine();
        sb.AppendLine($"{indent}    if (pageNumber < 1)");
        sb.AppendLine($"{indent}        throw new global::System.ArgumentOutOfRangeException(nameof(pageNumber), $\"{{nameof(pageNumber)}} can not be less than one\");");
        sb.AppendLine();
        sb.AppendLine($"{indent}    if (pageSize < 1)");
        sb.AppendLine($"{indent}        throw new global::System.ArgumentOutOfRangeException(nameof(pageSize), $\"{{nameof(pageSize)}} can not be less than one\");");
        sb.AppendLine();
        sb.AppendLine($"{indent}    return new {config.PageTypeName}<T>({pageCtorArgs});");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static IEnumerable<(string, string)> GetPageParamDocs(GeneratorConfig config, bool withPageSize)
    {
        yield return ("pageNumber", "page number");
        if (withPageSize) yield return ("pageSize", "page size");
        if (config.HasIncludeNestedMembers) yield return ("includeNestedMembers", "include nested members");
        if (config.HasAdditionalQueryFunc) yield return ("additionalQueryFunc", "");
    }

    private static void GenerateToPaginableAsync(StringBuilder sb, string indent, GeneratorConfig config, string constraint)
    {
        var src = SourceTypeName(config);
        var p = config.ToPaginableSourceParamName ?? config.SourceParamName;
        var sd = SourceDescriptor(config);
        var pd = PageDescriptor(config);
        var inm = config.HasIncludeNestedMembers ? "bool? includeNestedMembers = null" : "";
        var extraParams = string.IsNullOrEmpty(inm) ? "" : $", {inm}";
        var extraArgs = config.HasIncludeNestedMembers ? ", includeNestedMembers" : "";

        var docs = new List<(string, string)>
        {
            ("pageSize", "page size"),
            ("limitedMemberCount", "limited member count"),
        };
        if (config.HasIncludeNestedMembers) docs.Add(("includeNestedMembers", "include nested members"));
        docs.Add(("cancellationToken", "cancellation token"));

        AppendDoc(sb, indent, p, sd, "element type of your enumerable result", docs,
            ToPaginableAsyncExample(config, p),
            new[]
            {
                $"Make original {sd} result to {pd} collection asynchronously,",
                "with the total member count obtained via provider-native <c>CountAsync</c>.",
            },
            withExceptions: false, isAsync: true);
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task<{config.PaginableTypeName}<T>> ToPaginableAsync<T>(this {src} {p}, int? pageSize = null, int? limitedMemberCount = null{extraParams}, global::System.Threading.CancellationToken cancellationToken = default){constraint}");
        sb.AppendLine($"{indent}    => {config.FactoryTypeName}.CreatePageSetAsync({p}, pageSize, limitedMemberCount{extraArgs}{(config.ForwardAsyncCancellationToken ? ", cancellationToken" : "")});");
        sb.AppendLine();
    }

    private static void GenerateGetPageAsync(StringBuilder sb, string indent, GeneratorConfig config, string constraint)
    {
        if (string.IsNullOrEmpty(config.AsyncCountExpression) || string.IsNullOrEmpty(config.AsyncFetchExpression))
            return;

        var src = SourceTypeName(config);
        var p = config.SourceParamName;
        var sd = SourceDescriptor(config);
        var inm = config.HasIncludeNestedMembers ? "bool includeNestedMembers = false" : "";
        var extraParams = string.IsNullOrEmpty(inm) ? "" : $", {inm}";
        var returnsList = config.AsyncFetchReturnsList;
        var fetchMethod = config.AsyncFetchMethodName ?? "ToListAsync";

        var summary = new[]
        {
            $"Get specific page from original {sd} source with true end-to-end async:",
            "both the total member count (<c>CountAsync</c>) and the current page members",
            $"(<c>{fetchMethod}</c>) are executed as provider-native async database calls.",
        };
        var sourceParamDoc = $"original {sd} source";
        var typeParamDoc = $"element type of your {sd} source";
        var example = GetPageAsyncExample(config, p);

        var shortDocs = new List<(string, string)> { ("pageNumber", "page number") };
        if (config.HasIncludeNestedMembers) shortDocs.Add(("includeNestedMembers", "include nested members"));
        shortDocs.Add(("cancellationToken", "cancellation token"));

        AppendDoc(sb, indent, p, sourceParamDoc, typeParamDoc, shortDocs, example,
            summary, withExceptions: false, isAsync: true);
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task<IPage<T>> GetPageAsync<T>(this {src} {p}, int pageNumber{extraParams}, global::System.Threading.CancellationToken cancellationToken = default){constraint}");
        sb.AppendLine($"{indent}    => GetPageAsync({p}, pageNumber, PaginableSettingsManager.Settings.DefaultPageSize{(config.HasIncludeNestedMembers ? ", includeNestedMembers" : "")}{(config.ForwardAsyncCancellationToken ? ", cancellationToken" : "")});");
        sb.AppendLine();

        var longDocs = new List<(string, string)>
        {
            ("pageNumber", "page number"),
            ("pageSize", "page size"),
        };
        if (config.HasIncludeNestedMembers) longDocs.Add(("includeNestedMembers", "include nested members"));
        longDocs.Add(("cancellationToken", "cancellation token"));

        AppendDoc(sb, indent, p, sourceParamDoc, typeParamDoc, longDocs, example,
            summary, withExceptions: true, isAsync: true);
        sb.AppendLine($"{indent}public static async global::System.Threading.Tasks.Task<IPage<T>> GetPageAsync<T>(this {src} {p}, int pageNumber, int pageSize{extraParams}, global::System.Threading.CancellationToken cancellationToken = default){constraint}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    if ({p} is null)");
        sb.AppendLine($"{indent}        throw new global::System.ArgumentNullException(nameof({p}), $\"{{nameof({p})}} can not be null.\");");
        sb.AppendLine();
        sb.AppendLine($"{indent}    if (pageNumber < 1)");
        sb.AppendLine($"{indent}        throw new global::System.ArgumentOutOfRangeException(nameof(pageNumber), $\"{{nameof(pageNumber)}} can not be less than one\");");
        sb.AppendLine();
        sb.AppendLine($"{indent}    if (pageSize < 1)");
        sb.AppendLine($"{indent}        throw new global::System.ArgumentOutOfRangeException(nameof(pageSize), $\"{{nameof(pageSize)}} can not be less than one\");");
        sb.AppendLine();
        sb.AppendLine($"{indent}    var totalMemberCount = {config.AsyncCountExpression};");
        sb.AppendLine();
        sb.AppendLine($"{indent}    var skip = (pageNumber - 1) * pageSize;");
        sb.AppendLine($"{indent}    if (totalMemberCount > 0 && skip >= totalMemberCount)");
        sb.AppendLine($"{indent}        throw new global::System.ArgumentOutOfRangeException(nameof(pageNumber), $\"{{nameof(pageNumber)}} can not be greater than pages count\");");
        sb.AppendLine();

        if (returnsList)
        {
            sb.AppendLine($"{indent}    var members = {config.AsyncFetchExpression};");
            sb.AppendLine();
            sb.AppendLine($"{indent}    return new EnumerablePage<T>(members, pageNumber, pageSize, totalMemberCount, sourceIsFull: false);");
        }
        else
        {
            sb.AppendLine($"{indent}    return {config.AsyncFetchExpression};");
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private const string NewExampleLine = "\n";

    private static string Receiver(GeneratorConfig config, string paramName)
        => config.SourceExample ?? paramName;

    private static string ToPaginableExample(GeneratorConfig config, string paramName)
        => $"var paginable = {Receiver(config, paramName)}.ToPaginable();{NewExampleLine}var page = paginable.GetPage(15);";

    private static string GetPageExample(GeneratorConfig config, string paramName, bool withPageSize)
        => $"var page = {Receiver(config, paramName)}.GetPage(15{(withPageSize ? ", 50" : "")});{NewExampleLine}var totalMemberCount = page.TotalMemberCount;";

    private static string ToPaginableAsyncExample(GeneratorConfig config, string paramName)
        => $"var paginable = await {Receiver(config, paramName)}.ToPaginableAsync(50, cancellationToken: cancellationToken);{NewExampleLine}var page = paginable.GetPage(15);";

    private static string GetPageAsyncExample(GeneratorConfig config, string paramName)
        => $"var page = await {Receiver(config, paramName)}.GetPageAsync(15, 50, cancellationToken);{NewExampleLine}var totalMemberCount = page.TotalMemberCount;";

    private static string SourceDescriptor(GeneratorConfig config)
        => config.SourceDescriptor ?? StripGenerics(config.SourceTypeFullName);

    private static string SourceTypeName(GeneratorConfig config)
    {
        var full = config.SourceTypeFullName;
        var ns = ExtractNamespace(full);
        return ns is null || !full.StartsWith(ns + ".", StringComparison.Ordinal)
            ? full
            : full.Substring(ns.Length + 1);
    }

    private static string PageDescriptor(GeneratorConfig config)
        => config.PageDescriptor ?? config.PageTypeName;

    private static string StripGenerics(string fullTypeName)
    {
        var idx = fullTypeName.IndexOf('<');
        return idx >= 0 ? fullTypeName.Substring(0, idx) : fullTypeName;
    }

    private static string GetExtraParams(string aqf, string inm)
    {
        var parts = new[] { aqf, inm }.Where(s => !string.IsNullOrEmpty(s)).ToArray();
        return parts.Length == 0 ? "" : ", " + string.Join(", ", parts);
    }

    private static string GetExtraArgs(bool hasAqf, bool hasInm)
    {
        var parts = new[]
        {
            hasAqf ? "additionalQueryFunc: additionalQueryFunc" : "",
            hasInm ? "includeNestedMembers: includeNestedMembers" : "",
        }.Where(s => !string.IsNullOrEmpty(s)).ToArray();
        return parts.Length == 0 ? "" : ", " + string.Join(", ", parts);
    }

    private static string GetToPaginableForwardArgs(GeneratorConfig config)
    {
        var suffix = "";
        if (config.HasIncludeNestedMembers) suffix += ", includeNestedMembers: includeNestedMembers";
        if (config.ToPaginableHasAdditionalQueryFunc) suffix += ", additionalQueryFunc: additionalQueryFunc";
        return suffix;
    }

    private sealed record GeneratorConfig
    {
        public string Namespace { get; set; } = "";
        public string ClassName { get; set; } = "";
        public string OrmName { get; set; } = "";
        public string SourceTypeFullName { get; set; } = "";
        public string SourceParamName { get; set; } = "source";
        public string PageTypeName { get; set; } = "";
        public string PaginableTypeName { get; set; } = "";
        public string FactoryTypeName { get; set; } = "";
        public string HelperTypeName { get; set; } = "";
        public string? GenericConstraint { get; set; }
        public bool HasAdditionalQueryFunc { get; set; }
        public bool ToPaginableHasAdditionalQueryFunc { get; set; }
        public bool HasIncludeNestedMembers { get; set; }
        public bool HasAsync { get; set; }
        public string? AsyncCountExpression { get; set; }
        public string? AsyncFetchExpression { get; set; }
        public string? AsyncFetchMethodName { get; set; }
        public bool AsyncFetchReturnsList { get; set; }
        public bool SourceTypeIsNonGeneric { get; set; }
        public string? SyncCountCastExpression { get; set; }
        public string? ToPaginableSourceParamName { get; set; }
        public bool ForwardAsyncCancellationToken { get; set; } = true;
        public string? SourceDescriptor { get; set; }
        public string? PageDescriptor { get; set; }
        public string? SourceExample { get; set; }
    }
}
