<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Chloe.SqlServer" Version="5.56.0" />
    <PackageReference Include="FluentNHibernate" Version="3.5.0" />
    <PackageReference Include="FreeSql.Provider.SqlServer" Version="3.5.311" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.20" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="NHibernate" Version="5.7.0" />
    <PackageReference Include="Shouldly" Version="4.2.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\DotNetCore.Collections.Paginable.Chloe\DotNetCore.Collections.Paginable.Chloe.csproj" />
    <ProjectReference Include="..\..\src\DotNetCore.Collections.Paginable.DosOrm\DotNetCore.Collections.Paginable.DosOrm.csproj" />
    <ProjectReference Include="..\..\src\DotNetCore.Collections.Paginable.EntityFrameworkCore\DotNetCore.Collections.Paginable.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\DotNetCore.Collections.Paginable.FreeSql.DbContext\DotNetCore.Collections.Paginable.FreeSql.DbContext.csproj" />
    <ProjectReference Include="..\..\src\DotNetCore.Collections.Paginable.FreeSql\DotNetCore.Collections.Paginable.FreeSql.csproj" />
    <ProjectReference Include="..\..\src\DotNetCore.Collections.Paginable.NHibernate\DotNetCore.Collections.Paginable.NHibernate.csproj" />
    <ProjectReference Include="..\..\src\DotNetCore.Collections.Paginable.SqlKata\DotNetCore.Collections.Paginable.SqlKata.csproj" />
    <ProjectReference Include="..\..\src\DotNetCore.Collections.Paginable.SqlSugar\DotNetCore.Collections.Paginable.SqlSugar.csproj" />
  </ItemGroup>
</Project>
